[package]
name = "pexp"
version = "0.1.0"
edition = "2021"
rust-version = "1.59"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
